language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: w@28.io
  api_key:
    secure: ncww0mLUKiI0Ciu7raHvT5yEVfApmQRux1vUJggOA354I1l/jG19DOexjThnbZEtnxc9pTKsqmeTSrx+6ptymPENP3w/mhJeVJbknJ3pzgBhyxnuX8bbZNoGZI/c53y+8/FCJM+rtabVytT1UsYxIdp0MYDgPv4xgvKIzsdIveA=
  on:
    repo: wcandillon/swagger-js-codegen
    branch: master
    node: '0.11'
